---
title: "test"
author: "test"
geometry: left=2cm,right=2cm,top=0.5cm,bottom=1cm
output: pdf_document

---

```{r global-options, include=FALSE}

# 1: libraries
library(readr)
library(tidyverse)
library(lubridate)
library(CCAMLRGIS)
library(ccamlrtools)
library(knitr)
library(pander) #Need to install pandoc on your computer too

# 2 clean the working space
  rm(list=ls())

# 3 Load functions source files ( ‘ ~ / functions ’ )
  # check all files in the folder
  func_files <- list.files(path = "functions", full.names = T, recursive = T)
  # run all files listed as source
  suppressMessages(lapply(func_files, source))
  
# 4 Set chunck options for the whole document here
  # See str(knitr::opts_chunk$get()) for a list of default chunk options.
opts_chunk$set(fig.width=8, fig.height=4, dpi=200,cache=FALSE,
               highlight=F,echo=FALSE, warning=FALSE, message=FALSE)

# 5 Set some pander options to format tables (limited options)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('table.split.cells', Inf)
panderOptions('keep.trailing.zeros', TRUE)

# 6: Present the variables to simulate
    # s = 2021 #Just for tests. Season year. No default.
    # area = "RSR South 70" #Just for tests, no default this time   
    # area = "SRZ"
    # area = "SSRU 88.2 H"
    # area = "Research Block 88.2_2"
    # area = "Division 58.5.2"
    # area = "Ross Sea shelf survey area"
    # area = "Research Block 48.6_2"
    # area = "Subarea 88.1 and 882A–B"
    # area = "Subarea 48.2"
    # sp <- "Dissostichus mawsoni" #get species group with catch limits
    # sp <- "Dissostichus eleginoides" #get species group with catch limits
    # sp <- "Euphausia superba" #get species group with catch limits
    # alt_date = Sys.Date() %>% as.character() %>% as.POSIXct(tz = "UTC") #Instead of current date use other date as a standard to check for vms presence - could be useful for other areas during the season 
    # alt_date = "2020-04-02" %>% as.POSIXct(tz = "UTC")
    # type = "avg_day_cpue" #Can be changed to type = "avg_day_no_cpue"
    # change_vsls <- FALSE
    # days_project=100
    # rep_period <- NA

date_range <- as.Date(c(Sys.Date() - days(90), Sys.Date()))
date_range <- as.Date(c(as.Date("2020-07-01"), Sys.Date()))

d_tolerance <- 20
ca <- TRUE
end_date <- date_range[2]
start_date <- date_range[1]

```

```{r chunk name, results='asis'}

transhipments <- load_transhipments(start_date = start_date, end_date = end_date)
vessels_tranfer <- load_vessels() %>% 
  dplyr::select(c("VSL_Version_ID", Transferring_vessel_country = "CTY_ISO_3_Code"))

vessels_receive <- load_vessels() %>% 
  dplyr::select(c("VSL_Version_ID", Receiving_vessel_country = "CTY_ISO_3_Code"))

transhipments <- transhipments %>% 
  left_join(vessels_tranfer, by = c("Transferring_VSL_ID" = "VSL_Version_ID")) %>% 
  left_join(vessels_receive, by = c("Receiving_VSL_ID" = "VSL_Version_ID"))
  
#try alerts
transhipments_check_HMLR <- transhipments %>% 
  dplyr::filter(Includes_HMLR_B_F == 1) %>% 
  dplyr::mutate('Transfering vessel time difference (h)' = round(difftime(Notified_Start_Transfer_Date, Notified_Date_Receipt_Transferring_Vessel, units = "hours"), digits = 2), 'Receiving vessel time difference (h)' = round(difftime(Notified_Start_Transfer_Date,Notified_Date_Receipt_Receiving_Vessel, units = "hours"), digits = 2)) %>% 
  dplyr::select(THP_ID, 'Transferring vessel' = Transferring_vsl_name, 'Transferring country' = Transferring_vessel_country, 'Notification date: Tranferring vessel' = Notified_Date_Receipt_Transferring_Vessel, 'Receiving vessel' = Receiving_vsl_name, 'Receiving country' = Receiving_vessel_country, 'Notification date: Receiving vessel' = Notified_Date_Receipt_Receiving_Vessel, 'Notified transhipment start' = Notified_Start_Transfer_Date, 'Notified transhipment end' = Notified_End_Transfer_Date, 'Transfering vessel time difference (h)', 'Receiving vessel time difference (h)', Includes_HMLR_B_F) %>% 
  unique() %>% 
  dplyr::filter(`Transfering vessel time difference (h)` < 72 | `Receiving vessel time difference (h)` < 72)

transhipments_check_others <- transhipments %>% 
  dplyr::filter(Includes_HMLR_B_F == 0) %>% 
  dplyr::mutate('Transfering vessel time difference (h)' = round(difftime(Notified_Start_Transfer_Date, Notified_Date_Receipt_Transferring_Vessel, units = "hours"), digits = 2), 'Receiving vessel time difference (h)' = round(difftime(Notified_Start_Transfer_Date,Notified_Date_Receipt_Receiving_Vessel, units = "hours"), digits = 2)) %>% 
  dplyr::select(THP_ID, 'Transferring vessel' = Transferring_vsl_name, 'Transferring country' = Transferring_vessel_country, 'Notification date: Tranferring vessel' = Notified_Date_Receipt_Transferring_Vessel, 'Receiving vessel' = Receiving_vsl_name, 'Receiving country' = Receiving_vessel_country, 'Notification date: Receiving vessel' = Notified_Date_Receipt_Receiving_Vessel, 'Notified transhipment start' = Notified_Start_Transfer_Date, 'Notified transhipment end' = Notified_End_Transfer_Date, 'Transfering vessel time difference (h)', 'Receiving vessel time difference (h)', Includes_HMLR_B_F) %>% 
  unique() %>% 
  dplyr::filter(`Transfering vessel time difference (h)` < 2 | `Receiving vessel time difference (h)` < 2)

#Check on 3 bussiness day to confirm the transhipments
transhipments_check_confirmation <- transhipments %>% 
  dplyr::filter(THP_Status == "completed") %>% 
  dplyr::mutate(reference_date = Confirmed_Start_Transfer_Date)

      #Change the reference day for calculation according to what you have
      transhipments_check_confirmation$reference_date[which(is.na(transhipments_check_confirmation$reference_date))] <- transhipments_check_confirmation$Confirm_End_Transfer_Date[which(is.na(transhipments_check_confirmation$reference_date))]
      
     #Check on 3 bussiness day to confirm the transhipments
  transhipments_check_confirmation <- transhipments_check_confirmation %>% 
    dplyr::mutate(transferring_vessel_confirmation = round(difftime(Confirmed_Date_Receipt_Transferring_Vessel, reference_date, units = "days"), digits = 2), receiving_vessel_confirmation = round(difftime( Confirmed_Date_Receipt_Receiving_Vessel, reference_date, units = "days"), digits = 2)) %>% 
      dplyr::select(THP_ID, 'Transferring vessel' = Transferring_vsl_name, 'Transferring country' = Transferring_vessel_country, 'Confirmation date: Tranferring vessel' = Confirmed_Date_Receipt_Transferring_Vessel, 'Receiving vessel' = Receiving_vsl_name, 'Receiving country' = Receiving_vessel_country, 'Confirmation date: Receiving vessel' = Confirmed_Date_Receipt_Receiving_Vessel, 'Confirmed transhipment start' = Confirmed_Start_Transfer_Date, 'Confirmed transhipment end' = Confirm_End_Transfer_Date, 'Transfering vessel time difference (days)'= transferring_vessel_confirmation, 'Receiving vessel time difference (days)'= receiving_vessel_confirmation, Includes_HMLR_B_F, reference_date) %>% 
    unique() %>% 
    dplyr::filter(`Transfering vessel time difference (days)` > 3 | `Receiving vessel time difference (days)` > 3)

  week_function <- function(a, b) { 
    if (!is.na(b)) {
      sum(!weekdays(seq(a, b, "days")) %in% c("Saturday", "Sunday"))
    } else {
        NA
    }
  }

  Nweekdays <- Vectorize(week_function)
  
transhipments_check_confirmation <- transhipments_check_confirmation %>% 
  mutate("Receiving vessel: weekdays" = Nweekdays(reference_date, `Confirmation date: Receiving vessel`), "Transferring vessel: weekdays" = Nweekdays(reference_date, `Confirmation date: Tranferring vessel`))
  
```

```{r por-inspections, results='asis'}

port_inspections <- check_port_inspections(start_date, end_date, d_tolerance, ca)

port_inspections$dcd_port_inspected

port_inspections$pi_missing


```
